### ISSUE TITLE
Minimal width of screenshot

### ISSUE THREAD

**Issue by josephbuchma** [abhisheksoni27/code-snipper#1]
Hi. I'm looking for an option to specify minimal width for snippet (image). I was browsing through webshot's options list, and it looks like it doesn't support it (that's why it's an issue and not a PR). 
Any ideas ?

**Comment by abhisheksoni27** [comment]
I believe you can do this by passing a width parameter and then crop the image to that desired width using 
imagemagick.

See this: https://github.com/abhisheksoni27/code-snipper/blob/master/code-snipper.js#L196

This might be a great opportunity for a PR?

**Comment by robbieferrero** [comment]
This issue should now be fixed with the `webshotCustomConfig` options outlined in the README

**Comment by abhisheksoni27** [comment]
Yes, great!
